const DEFAULT_MOVES = [
  { id: 1, name: 'Punch', damage: 15, tier: 'low', type: 'physical', description: 'A basic punch attack', effects: [], energyCost: 5, cooldown: 0, isActive: true },
  { id: 2, name: 'Kick', damage: 20, tier: 'low', type: 'physical', description: 'A swift kick', effects: [], energyCost: 8, cooldown: 0, isActive: true },
  { id: 3, name: 'Block', damage: 0, tier: 'low', type: 'defensive', description: 'Block incoming attacks', effects: ['block'], energyCost: 5, cooldown: 1, isActive: true },
  { id: 4, name: 'Swipe', damage: 22, tier: 'low', type: 'physical', description: 'A quick swipe attack', effects: [], energyCost: 8, cooldown: 0, isActive: true },
  { id: 5, name: 'Charge', damage: 0, tier: 'low', type: 'buff', description: 'Charge up power for next attack', effects: ['powerUp'], energyCost: 10, cooldown: 1, isActive: true },
  { id: 6, name: 'Heal', damage: -15, tier: 'low', type: 'healing', description: 'Restore some HP', effects: ['heal'], energyCost: 15, cooldown: 2, isActive: true },
  { id: 7, name: 'Taunt', damage: 0, tier: 'low', type: 'debuff', description: 'Taunt the enemy', effects: ['taunt'], energyCost: 5, cooldown: 2, isActive: true },
  { id: 8, name: 'Smack', damage: 25, tier: 'low', type: 'physical', description: 'A strong smack', effects: [], energyCost: 10, cooldown: 0, isActive: true },
  { id: 9, name: 'Focus', damage: 0, tier: 'low', type: 'buff', description: 'Increase accuracy', effects: ['focus'], energyCost: 8, cooldown: 1, isActive: true },
  { id: 10, name: 'Jab', damage: 18, tier: 'low', type: 'physical', description: 'A quick jab', effects: [], energyCost: 6, cooldown: 0, isActive: true },

  { id: 11, name: 'Strike', damage: 40, tier: 'mid', type: 'physical', description: 'A powerful strike', effects: [], energyCost: 15, cooldown: 0, isActive: true },
  { id: 12, name: 'Double Hit', damage: 45, tier: 'mid', type: 'physical', description: 'Hit twice in succession', effects: ['multiHit'], energyCost: 18, cooldown: 0, isActive: true },
  { id: 13, name: 'Wind Cut', damage: 50, tier: 'mid', type: 'elemental', description: 'Slash with wind energy', effects: [], energyCost: 20, cooldown: 0, isActive: true },
  { id: 14, name: 'Guard', damage: 0, tier: 'mid', type: 'defensive', description: 'Strong defensive stance', effects: ['guard'], energyCost: 12, cooldown: 2, isActive: true },
  { id: 15, name: 'Power Up', damage: 0, tier: 'mid', type: 'buff', description: 'Boost attack power significantly', effects: ['powerUp', 'attackBoost'], energyCost: 20, cooldown: 2, isActive: true },
  { id: 16, name: 'Recover', damage: -30, tier: 'mid', type: 'healing', description: 'Recover moderate HP', effects: ['heal'], energyCost: 25, cooldown: 3, isActive: true },
  { id: 17, name: 'Flame Hit', damage: 50, tier: 'mid', type: 'fire', description: 'Strike with fire', effects: ['burn'], energyCost: 22, cooldown: 0, isActive: true },
  { id: 18, name: 'Frost Hit', damage: 48, tier: 'mid', type: 'ice', description: 'Strike with ice', effects: ['freeze'], energyCost: 22, cooldown: 0, isActive: true },
  { id: 19, name: 'Shock Hit', damage: 52, tier: 'mid', type: 'electric', description: 'Strike with lightning', effects: ['paralyze'], energyCost: 24, cooldown: 0, isActive: true },
  { id: 20, name: 'Counter', damage: 35, tier: 'mid', type: 'physical', description: 'Counter enemy attack', effects: ['counter'], energyCost: 15, cooldown: 1, isActive: true },

  { id: 21, name: 'Smash', damage: 80, tier: 'high', type: 'physical', description: 'A devastating smash', effects: [], energyCost: 30, cooldown: 1, isActive: true },
  { id: 22, name: 'Meteor', damage: 100, tier: 'high', type: 'fire', description: 'Call down a meteor', effects: ['burn'], energyCost: 40, cooldown: 2, isActive: true },
  { id: 23, name: 'Flash', damage: 95, tier: 'high', type: 'light', description: 'Blinding flash attack', effects: ['blind'], energyCost: 38, cooldown: 1, isActive: true },
  { id: 24, name: 'Slice', damage: 85, tier: 'high', type: 'physical', description: 'Sharp slicing attack', effects: ['bleed'], energyCost: 32, cooldown: 0, isActive: true },
  { id: 25, name: 'Flame Burst', damage: 90, tier: 'high', type: 'fire', description: 'Explosive fire burst', effects: ['burn'], energyCost: 35, cooldown: 1, isActive: true },
  { id: 26, name: 'Wave', damage: 88, tier: 'high', type: 'water', description: 'Powerful water wave', effects: [], energyCost: 34, cooldown: 1, isActive: true },
  { id: 27, name: 'Thunder', damage: 95, tier: 'high', type: 'electric', description: 'Lightning strike', effects: ['paralyze'], energyCost: 38, cooldown: 1, isActive: true },
  { id: 28, name: 'Quake', damage: 100, tier: 'high', type: 'earth', description: 'Earthquake attack', effects: ['stun'], energyCost: 42, cooldown: 2, isActive: true },
  { id: 29, name: 'Revive', damage: -60, tier: 'high', type: 'healing', description: 'Major HP restoration', effects: ['heal'], energyCost: 45, cooldown: 4, isActive: true },
  { id: 30, name: 'Boost', damage: 0, tier: 'high', type: 'buff', description: 'Major stat boost', effects: ['allBoost'], energyCost: 35, cooldown: 3, isActive: true },

  { id: 101, name: 'Claw Rush', damage: 90, tier: 'special', characterName: 'Bali', type: 'physical', description: 'Bali special attack', effects: [], energyCost: 35, cooldown: 2, isActive: true },
  { id: 102, name: 'Sonic Peck', damage: 85, tier: 'special', characterName: 'Betsy', type: 'physical', description: 'Betsy special attack', effects: [], energyCost: 32, cooldown: 2, isActive: true },
  { id: 103, name: 'Power Slam', damage: 100, tier: 'special', characterName: 'Bruce', type: 'physical', description: 'Bruce special attack', effects: ['stun'], energyCost: 40, cooldown: 2, isActive: true },
  { id: 104, name: 'Horn Charge', damage: 95, tier: 'special', characterName: 'Buck', type: 'physical', description: 'Buck special attack', effects: [], energyCost: 38, cooldown: 2, isActive: true },
  { id: 105, name: 'Happy Howl', damage: 85, tier: 'special', characterName: 'Buddy', type: 'sound', description: 'Buddy special attack', effects: ['buff'], energyCost: 32, cooldown: 2, isActive: true },
  { id: 106, name: 'Leaf Shot', damage: 88, tier: 'special', characterName: 'Caly', type: 'nature', description: 'Caly special attack', effects: [], energyCost: 34, cooldown: 2, isActive: true },
  { id: 107, name: 'Shell Roll', damage: 90, tier: 'special', characterName: 'Dillo', type: 'physical', description: 'Dillo special attack', effects: ['defense'], energyCost: 35, cooldown: 2, isActive: true },
  { id: 108, name: 'Charm Spin', damage: 88, tier: 'special', characterName: 'Donna', type: 'physical', description: 'Donna special attack', effects: ['charm'], energyCost: 34, cooldown: 2, isActive: true },
  { id: 109, name: 'Royal Cut', damage: 95, tier: 'special', characterName: 'Duke', type: 'physical', description: 'Duke special attack', effects: [], energyCost: 38, cooldown: 2, isActive: true },
  { id: 110, name: 'Hot Punch', damage: 90, tier: 'special', characterName: 'Earl', type: 'fire', description: 'Earl special attack', effects: ['burn'], energyCost: 35, cooldown: 2, isActive: true },
  { id: 111, name: 'Web Strike', damage: 85, tier: 'special', characterName: 'Edna', type: 'physical', description: 'Edna special attack', effects: ['slow'], energyCost: 32, cooldown: 2, isActive: true },
  { id: 112, name: 'Petal Wave', damage: 88, tier: 'special', characterName: 'Elaine', type: 'nature', description: 'Elaine special attack', effects: [], energyCost: 34, cooldown: 2, isActive: true },
  { id: 113, name: 'Sparkle Beam', damage: 90, tier: 'special', characterName: 'Faye', type: 'light', description: 'Faye special attack', effects: [], energyCost: 35, cooldown: 2, isActive: true },
  { id: 114, name: 'Tidal Wave', damage: 95, tier: 'special', characterName: 'Finn', type: 'water', description: 'Finn special attack', effects: [], energyCost: 38, cooldown: 2, isActive: true },
  { id: 115, name: 'Head Smash', damage: 100, tier: 'special', characterName: 'Frank', type: 'physical', description: 'Frank special attack', effects: ['stun'], energyCost: 40, cooldown: 2, isActive: true },
  { id: 116, name: 'Wild Leap', damage: 92, tier: 'special', characterName: 'Fuzzy', type: 'physical', description: 'Fuzzy special attack', effects: [], energyCost: 36, cooldown: 2, isActive: true },
  { id: 117, name: 'Volt Bite', damage: 95, tier: 'special', characterName: 'Henry', type: 'electric', description: 'Henry special attack', effects: ['paralyze'], energyCost: 38, cooldown: 2, isActive: true },
  { id: 118, name: 'Healing Ray', damage: -80, tier: 'special', characterName: 'Iris', type: 'healing', description: 'Iris special attack', effects: ['heal'], energyCost: 40, cooldown: 3, isActive: true },
  { id: 119, name: 'Sneak Cut', damage: 90, tier: 'special', characterName: 'Jack', type: 'physical', description: 'Jack special attack', effects: ['crit'], energyCost: 35, cooldown: 2, isActive: true },
  { id: 120, name: 'Stone Punch', damage: 92, tier: 'special', characterName: 'Jade', type: 'earth', description: 'Jade special attack', effects: [], energyCost: 36, cooldown: 2, isActive: true },
  { id: 121, name: 'Light Shot', damage: 85, tier: 'special', characterName: 'Joy', type: 'light', description: 'Joy special attack', effects: [], energyCost: 32, cooldown: 2, isActive: true },
  { id: 122, name: 'Sneaky Swipe', damage: 88, tier: 'special', characterName: 'Larry', type: 'physical', description: 'Larry special attack', effects: [], energyCost: 34, cooldown: 2, isActive: true },
  { id: 123, name: 'Sound Blast', damage: 90, tier: 'special', characterName: 'Lennon', type: 'sound', description: 'Lennon special attack', effects: ['confuse'], energyCost: 35, cooldown: 2, isActive: true },
  { id: 124, name: 'Fire Breath', damage: 95, tier: 'special', characterName: 'Lizzy', type: 'fire', description: 'Lizzy special attack', effects: ['burn'], energyCost: 38, cooldown: 2, isActive: true },
  { id: 125, name: 'Laser Beam', damage: 100, tier: 'special', characterName: 'Louie', type: 'light', description: 'Louie special attack', effects: [], energyCost: 40, cooldown: 2, isActive: true },
  { id: 126, name: 'Fist Storm', damage: 92, tier: 'special', characterName: 'Max', type: 'physical', description: 'Max special attack', effects: ['multiHit'], energyCost: 36, cooldown: 2, isActive: true },
  { id: 127, name: 'Vine Wrap', damage: 88, tier: 'special', characterName: 'Milo', type: 'nature', description: 'Milo special attack', effects: ['bind'], energyCost: 34, cooldown: 2, isActive: true },
  { id: 128, name: 'Bubble Shot', damage: 85, tier: 'special', characterName: 'Molly', type: 'water', description: 'Molly special attack', effects: [], energyCost: 32, cooldown: 2, isActive: true },
  { id: 129, name: 'Spin Dash', damage: 90, tier: 'special', characterName: 'Nico', type: 'physical', description: 'Nico special attack', effects: [], energyCost: 35, cooldown: 2, isActive: true },
  { id: 130, name: 'Moon Strike', damage: 88, tier: 'special', characterName: 'Nina', type: 'dark', description: 'Nina special attack', effects: [], energyCost: 34, cooldown: 2, isActive: true },
  { id: 131, name: 'Frost Bite', damage: 95, tier: 'special', characterName: 'Nix', type: 'ice', description: 'Nix special attack', effects: ['freeze'], energyCost: 38, cooldown: 2, isActive: true },
  { id: 132, name: 'Fire Burst', damage: 92, tier: 'special', characterName: 'Ollie', type: 'fire', description: 'Ollie special attack', effects: ['burn'], energyCost: 36, cooldown: 2, isActive: true },
  { id: 133, name: 'Wind Kick', damage: 90, tier: 'special', characterName: 'Paco', type: 'wind', description: 'Paco special attack', effects: [], energyCost: 35, cooldown: 2, isActive: true },
  { id: 134, name: 'Gear Spin', damage: 95, tier: 'special', characterName: 'Paolo', type: 'physical', description: 'Paolo special attack', effects: [], energyCost: 38, cooldown: 2, isActive: true },
  { id: 135, name: 'Spice Bomb', damage: 88, tier: 'special', characterName: 'Pepper', type: 'fire', description: 'Pepper special attack', effects: ['burn'], energyCost: 34, cooldown: 2, isActive: true },
  { id: 136, name: 'Mind Push', damage: 90, tier: 'special', characterName: 'Phil', type: 'psychic', description: 'Phil special attack', effects: ['confuse'], energyCost: 35, cooldown: 2, isActive: true },
  { id: 137, name: 'Night Grip', damage: 90, tier: 'special', characterName: 'Poe', type: 'dark', description: 'Poe special attack', effects: [], energyCost: 35, cooldown: 2, isActive: true },
  { id: 138, name: 'Speed Cut', damage: 88, tier: 'special', characterName: 'Quinn', type: 'physical', description: 'Quinn special attack', effects: [], energyCost: 34, cooldown: 2, isActive: true },
  { id: 139, name: 'Storm Jab', damage: 92, tier: 'special', characterName: 'Ravi', type: 'electric', description: 'Ravi special attack', effects: [], energyCost: 36, cooldown: 2, isActive: true },
  { id: 140, name: 'Rock Toss', damage: 90, tier: 'special', characterName: 'Rocky', type: 'earth', description: 'Rocky special attack', effects: [], energyCost: 35, cooldown: 2, isActive: true },
  { id: 141, name: 'Heart Blast', damage: 85, tier: 'special', characterName: 'Romeo', type: 'light', description: 'Romeo special attack', effects: ['charm'], energyCost: 32, cooldown: 2, isActive: true },
  { id: 142, name: 'Gem Strike', damage: 88, tier: 'special', characterName: 'Rubie', type: 'physical', description: 'Rubie special attack', effects: [], energyCost: 34, cooldown: 2, isActive: true },
  { id: 143, name: 'Shell Guard', damage: 0, tier: 'special', characterName: 'Shelly', type: 'defensive', description: 'Shelly special attack', effects: ['shield'], energyCost: 30, cooldown: 2, isActive: true },
  { id: 144, name: 'Hop Smash', damage: 90, tier: 'special', characterName: 'Skippy', type: 'physical', description: 'Skippy special attack', effects: [], energyCost: 35, cooldown: 2, isActive: true },
  { id: 145, name: 'Hammer Hit', damage: 95, tier: 'special', characterName: 'Steve', type: 'physical', description: 'Steve special attack', effects: ['stun'], energyCost: 38, cooldown: 2, isActive: true },
  { id: 146, name: 'Star Beam', damage: 88, tier: 'special', characterName: 'Suzy', type: 'light', description: 'Suzy special attack', effects: [], energyCost: 34, cooldown: 2, isActive: true },
  { id: 147, name: 'Twin Spin', damage: 95, tier: 'special', characterName: 'Tony', type: 'physical', description: 'Tony special attack', effects: ['multiHit'], energyCost: 38, cooldown: 2, isActive: true },
  { id: 148, name: 'Tide Crash', damage: 95, tier: 'special', characterName: 'Ursula', type: 'water', description: 'Ursula special attack', effects: [], energyCost: 38, cooldown: 2, isActive: true },
  { id: 149, name: 'Floral Blast', damage: 88, tier: 'special', characterName: 'Wanda', type: 'nature', description: 'Wanda special attack', effects: [], energyCost: 34, cooldown: 2, isActive: true },
  { id: 150, name: 'Sand Rush', damage: 90, tier: 'special', characterName: 'Yara', type: 'earth', description: 'Yara special attack', effects: [], energyCost: 35, cooldown: 2, isActive: true },
  { id: 151, name: 'Steel Slam', damage: 100, tier: 'special', characterName: 'Zac', type: 'physical', description: 'Zac special attack', effects: ['stun'], energyCost: 40, cooldown: 2, isActive: true }
];

const MOVE_TYPES = ['physical', 'fire', 'water', 'ice', 'electric', 'earth', 'wind', 'nature', 'light', 'dark', 'psychic', 'sound', 'healing', 'defensive', 'buff', 'debuff', 'elemental'];
const MOVE_TIERS = ['low', 'mid', 'high', 'special'];
const MOVE_EFFECTS = ['burn', 'freeze', 'paralyze', 'stun', 'confuse', 'charm', 'blind', 'bleed', 'slow', 'bind', 'heal', 'block', 'guard', 'shield', 'powerUp', 'attackBoost', 'defenseBoost', 'speedBoost', 'allBoost', 'focus', 'taunt', 'counter', 'crit', 'multiHit', 'defense'];

const ST_THRESHOLDS = {
  low: { min: 0, max: 40 },
  mid: { min: 41, max: 75 },
  high: { min: 76, max: 100 }
};

module.exports = {
  DEFAULT_MOVES,
  MOVE_TYPES,
  MOVE_TIERS,
  MOVE_EFFECTS,
  ST_THRESHOLDS
};
